name: Build Unbound for Windows (Latest Release)

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 0 * * 0'  # Weekly check for new releases

jobs:
  build:
    runs-on: windows-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Fetch latest release tarball URL
        id: get-release
        run: |
          $url = "https://api.github.com/repos/NLnetLabs/unbound/releases/latest "
          $response = Invoke-RestMethod -Uri $url -Headers @{"Authorization"="Bearer $env:GITHUB_TOKEN"}
          $tarballUrl = $response.tarball_url
          $version = $response.tag_name
          echo "TARBALL_URL=$tarballUrl" >> $env:GITHUB_ENV
          echo "VERSION=$version" >> $env:GITHUB_ENV

      - name: Download and extract tarball
        run: |
          $dest = "$env:GITHUB_WORKSPACE/unbound"
          $uri = "$env:TARBALL_URL"
          curl.exe -L -o unbound.tar.gz "$uri"
          mkdir "$dest"
          tar.exe -xzf unbound.tar.gz -C "$dest" --strip-components=1

      - name: Install winflexbison3
        run: |
          choco install winflexbison3 -y

      - name: Set environment variables
        run: |
          $env:LEX = "win_flex"
          $env:YACC = "win_bison -y"
          $env:unboundpath = "$env:GITHUB_WORKSPACE/unbound"
          $env:prepath = "$env:GITHUB_WORKSPACE"

      - name: Build OpenSSL
        run: |
          mkdir "$env:prepath/openssl"
          curl.exe -L -k -o openssl-3.2.0.tar.gz https://www.openssl.org/source/openssl-3.2.0.tar.gz 
          tar.exe -xzf openssl-3.2.0.tar.gz -C "$env:prepath"
          cd "$env:prepath/openssl-3.2.0"
          C:/msys64/usr/bin/perl.exe ./Configure no-shared no-asm -DOPENSSL_NO_CAPIENG mingw64 --prefix="$env:prepath/openssl" PERL="C:/msys64/usr/bin/perl"
          make.exe build_libs
          cp Makefile Makefile.orig
          sed.exe -e "s?^INSTALLTOP=.*$?INSTALLTOP=$env:prepath/openssl?" Makefile.orig > Makefile
          make.exe install_dev

      - name: Build Expat
        run: |
          $LIBEXPAT_FNAME = "expat-2.7.0"
          $LIBEXPAT_VERSION_DIR = "R_2_7_0"
          mkdir "$env:prepath/expat"
          curl.exe -L -k -o "$LIBEXPAT_FNAME.tar.gz" "https://github.com/libexpat/libexpat/releases/download/ $LIBEXPAT_VERSION_DIR/$LIBEXPAT_FNAME.tar.gz"
          tar.exe -xzf "$LIBEXPAT_FNAME.tar.gz" -C "$env:prepath"
          cd "$env:prepath/$LIBEXPAT_FNAME"
          ./configure SHELL=/usr/bin/bash CONFIG_SHELL=/usr/bin/bash --prefix="$env:prepath/expat" --exec-prefix="$env:prepath/expat" --bindir="$env:prepath/expat/bin" --includedir="$env:prepath/expat/include" --mandir="$env:prepath/expat/man" --libdir="$env:prepath/expat/lib"
          make.exe
          make.exe install

      - name: Configure and build Unbound
        working-directory: ${{ env.unboundpath }}
        shell: bash
        run: |
          ./configure --enable-debug --enable-static-exe --disable-flto "--with-ssl=$env:prepath/openssl" "--with-libexpat=$env:prepath/expat" --disable-shared
          make.exe
          make.exe test

      - name: Archive binaries
        uses: actions/upload-artifact@v4
        with:
          name: unbound-windows
          path: ${{ env.unboundpath }}/util/*.exe
